### ISSUE TITLE
Petition Page - Progress Bar

### ISSUE THREAD

**Issue by tyler310** [CodeTheChangeUBC/represent-the-10#5]
This story is tied to the **Epic [#4]**, Petition Page.

As as a user, I want to know how many people have signed this petition so I know how much traction it has.

# **Features**

- Progress bar should automatically update based on number of signatures
- Dots on the progress bar should represent milestones and/or facts about the deaf community (discussed with client, feature requirement)
- Hovering over the dots should show a quick fact/blurb about the community

# **Tasks**

- [x] Display empty progress bar with markers showing progess
- [x] Use AJAX calls to get petition information
- [x] Parse petition information and display signatures as it progresses live
- [ ] Create milestone dots on the progress bar based on numbers they represent
- [x] Show facts/information on hover over dots

# **Notes**
- We can host this petition anywhere we want, it simply must store all the information that is asked for
