### ISSUE TITLE
Petition Page - Languages and Paragraph

### ISSUE THREAD

**Issue by tyler310** [CodeTheChangeUBC/represent-the-10#6]
This story is tied to the **Epic [#4]**, Petition Page.

As a user, I want to find out what the petition is for so I know whether I want to support it.

As a non-English speaking user, I want to be able to read the petition in my language.

# **Features**
- All petition information should be displayed at once, in one block
- Petition should support four languages:
  - English
  - French
  - ASL
  - LSQ
- Languages should be toggled based on which language is selected
  - English website should default to English language
  - French website should default to French language
  - As per the client, the selected language does not need to be cached

# **Tasks**

- [x] Display petition information in paragraphs
- [x] Language toggles for English, French, ASL, LSQ
- [ ] Language must be able to default to a specific language (English or French)

**Comment by EWaterman** [comment]
To finish this issue have: on doc load show all the divs with the default language text (meaning all the divs with the class "english" or "french" for example.

**Comment by EWaterman** [comment]
Relates to #14
