### ISSUE TITLE
Petition Page - Signing the Petition

### ISSUE THREAD

**Issue by tyler310** [CodeTheChangeUBC/represent-the-10#7]
This story is tied to the Epic [#4], Petition Page.

As a person who supports the deaf community, I want to be able to sign the petition so that I can be a part of the movement.

# **Features**
- Form must be inline on the website
- Multilingual - Fields labeled in English and French (eg. Name/Nom)
- The following fields must be supported and are all required (translations coming soon):
  - First Name
  - Last Name
  - Address
  - City
  - Province/Territory
  - Postal Code
- Duplicate checking should be done on all fields; if one field is different, signature should be accepted
- Petition can be hosted anywhere, but must support all the information from above

# **Tasks**
- [x] Find a place to host the petition
- [x] Display inline form with dual language support
- [x] AJAX submission of all data above to petition API
- [x] Ensure that if the exact information is submitted twice, user is notified and petition is not signed
